-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 15:48:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tiendargenta_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendargenta_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendargenta_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `tiendargenta_db` ;

-- -----------------------------------------------------
-- Table `tiendargenta_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `dni` INT(11) NULL DEFAULT NULL,
  `telefono` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `rolId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rolId` (`rolId` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`rolId`)
    REFERENCES `tiendargenta_db`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`subcategorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  `descuento` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `categoriasId` INT(11) NOT NULL,
  `subCategoriasId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriasId` (`categoriasId` ASC) VISIBLE,
  INDEX `subCategoriasId` (`subCategoriasId` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoriasId`)
    REFERENCES `tiendargenta_db`.`categorias` (`id`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`subCategoriasId`)
    REFERENCES `tiendargenta_db`.`subcategorias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`carritos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuariosId` INT(11) NOT NULL,
  `productosId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuariosId` (`usuariosId` ASC) VISIBLE,
  INDEX `productosId` (`productosId` ASC) VISIBLE,
  CONSTRAINT `carritos_ibfk_1`
    FOREIGN KEY (`usuariosId`)
    REFERENCES `tiendargenta_db`.`usuarios` (`id`),
  CONSTRAINT `carritos_ibfk_2`
    FOREIGN KEY (`productosId`)
    REFERENCES `tiendargenta_db`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`historiales` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `categoriasId` INT(11) NOT NULL,
  `subCategoriasId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriasId` (`categoriasId` ASC) VISIBLE,
  INDEX `subCategoriasId` (`subCategoriasId` ASC) VISIBLE,
  CONSTRAINT `historiales_ibfk_1`
    FOREIGN KEY (`categoriasId`)
    REFERENCES `tiendargenta_db`.`categorias` (`id`),
  CONSTRAINT `historiales_ibfk_2`
    FOREIGN KEY (`subCategoriasId`)
    REFERENCES `tiendargenta_db`.`subcategorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`historialesimagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`historialesimagenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `historialId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `historialId` (`historialId` ASC) VISIBLE,
  CONSTRAINT `historialesimagenes_ibfk_1`
    FOREIGN KEY (`historialId`)
    REFERENCES `tiendargenta_db`.`historiales` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`imagenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `productosId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productosId` (`productosId` ASC) VISIBLE,
  CONSTRAINT `imagenes_ibfk_1`
    FOREIGN KEY (`productosId`)
    REFERENCES `tiendargenta_db`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`ordenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuariosId` INT(11) NOT NULL,
  `carritosId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuariosId` (`usuariosId` ASC) VISIBLE,
  INDEX `carritosId` (`carritosId` ASC) VISIBLE,
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`usuariosId`)
    REFERENCES `tiendargenta_db`.`usuarios` (`id`),
  CONSTRAINT `ordenes_ibfk_2`
    FOREIGN KEY (`carritosId`)
    REFERENCES `tiendargenta_db`.`carritos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tiendargenta_db`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendargenta_db`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
