-- MySQL Script generated by MySQL Workbench
-- Fri Oct  7 20:33:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendArgenta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendArgenta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendArgenta` DEFAULT CHARACTER SET utf8 ;
USE `tiendArgenta` ;

-- -----------------------------------------------------
-- Table `tiendArgenta`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`subCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`subCategoria` (
  `idsubCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `descuento` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Categorias_id` INT NOT NULL,
  `subCategoria_idsubCategoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productos_Categorias1_idx` (`Categorias_id` ASC) VISIBLE,
  INDEX `fk_Productos_subCategoria1_idx` (`subCategoria_idsubCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`Categorias_id`)
    REFERENCES `tiendArgenta`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_subCategoria1`
    FOREIGN KEY (`subCategoria_idsubCategoria`)
    REFERENCES `tiendArgenta`.`subCategoria` (`idsubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `Productos_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Imagenes_Productos_idx` (`Productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Imagenes_Productos`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `tiendArgenta`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Historiales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `descuento` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Categorias_id` INT NOT NULL,
  `subCategoria_idsubCategoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Historiales_Categorias1_idx` (`Categorias_id` ASC) VISIBLE,
  INDEX `fk_Historiales_subCategoria1_idx` (`subCategoria_idsubCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Historiales_Categorias1`
    FOREIGN KEY (`Categorias_id`)
    REFERENCES `tiendArgenta`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historiales_subCategoria1`
    FOREIGN KEY (`subCategoria_idsubCategoria`)
    REFERENCES `tiendArgenta`.`subCategoria` (`idsubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Imagen_Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Imagen_Historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Historiales_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Imagenes_Historiales_Historiales1_idx` (`Historiales_id` ASC) VISIBLE,
  CONSTRAINT `fk_Imagenes_Historiales_Historiales1`
    FOREIGN KEY (`Historiales_id`)
    REFERENCES `tiendArgenta`.`Historiales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `dni` INT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Productos_id` INT NOT NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carritos_Productos1_idx` (`Productos_id` ASC) VISIBLE,
  INDEX `fk_Carritos_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carritos_Productos1`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `tiendArgenta`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carritos_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `tiendArgenta`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`Ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`Ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Carritos_id` INT NOT NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ordenes_Carritos1_idx` (`Carritos_id` ASC) VISIBLE,
  INDEX `fk_Ordenes_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ordenes_Carritos1`
    FOREIGN KEY (`Carritos_id`)
    REFERENCES `tiendArgenta`.`Carrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordenes_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `tiendArgenta`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `admin` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol`),
  INDEX `fk_rol_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_rol_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `tiendArgenta`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendArgenta`.`metodosDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendArgenta`.`metodosDePago` (
  `idmetodosDePago` INT NOT NULL AUTO_INCREMENT,
  `Ordenes_id` INT NOT NULL,
  PRIMARY KEY (`idmetodosDePago`),
  INDEX `fk_metodosDePago_Ordenes1_idx` (`Ordenes_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodosDePago_Ordenes1`
    FOREIGN KEY (`Ordenes_id`)
    REFERENCES `tiendArgenta`.`Ordenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
